"""Build every simulation table of the paper from the result files in simulation_results/.

    python tables/all_tables.py                 # all tables, a few seconds

Output, named by the paper's numbering (main text: Tables 1-5; Online Appendix: A2-A4):
    tables/Table_<n>.tex   LaTeX tabular in the paper's layout: row order, labels, columns and rounding as printed

    Table 1   Panel A  table_1_models.json          (simulation_codes/table_1_models.py)
              Panel B  table_5_supply.json          (simulation_codes/table_5_supply.py)
              Panel C  table_4_extra_models.json    (simulation_codes/table_4_extra_models.py)
    Table 2            table_6_literature.json      (simulation_codes/table_6_literature.py)
    Table 3            table_6_baseline_pricing.json (simulation_codes/table_6_baseline_pricing.py)
    Table 4   Panel A  table_2_scalability.json     (simulation_codes/table_2_scalability.py)
              Panel B  table_2_scalability_20.json  (simulation_codes/table_2_scalability_20.py)
    Table 5            table_3_tuning_full.json + table_3_tuning_full_extended.json, own elasticity
                       (also written as tables/table_3_opt_tuning_own.csv, the input of Figure A2)
    Table A2           table_A2_robustness.json     (simulation_codes/table_A2_robustness.py)
    Table A3  Panel A  table_3_tuning_full.json + table_3_tuning_full_extended.json, cross elasticity
              Panel B  table_3_tuning_reduced_form.json
    Table A4           table_A4_extra_primitives.json (simulation_codes/table_A4_extra_primitives.py)

Table A1 lists calibration inputs (simulation_results/calibrated_params.json, from
calibrate_literature.py). Table 6, Table A5 and Figure 2 are produced in ../empirical/.
"""
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import csv
import json
import statistics

RES = "./simulation_results"
OUT = "./tables"
WRITTEN = []

MODELS_A = [("Logit", "Logit"), ("BLP_ind", "Independent RC Logit"), ("BLP_corr", "Correlated RC Logit")]
MODELS_B = [("sim_logit", "Logit"), ("sim_ind", "Independent RC Logit"), ("sim_corr", "Correlated RC Logit")]
MODELS_C = [("Complements", "Complementarity"), ("Variety", "Variety and Quantity")]
OBS = [10_000, 20_000, 40_000, 60_000]
PRODUCTS = list(range(4, 21, 2))


def load(name):
    with open(f"{RES}/{name}") as f:
        return json.load(f)


def f3(x):
    s = f"{x:.3f}"
    return "0.000" if s == "-0.000" else s


def fnum(x, d):
    s = f"{x:.{d}f}"
    return s.lstrip("-") if float(s) == 0 else s


def summary(iterations):
    """True value, mean estimate, bias, mean bootstrap SE and SD of estimates, for own and cross."""
    out = {}
    for kind in ("own", "cross"):
        true = statistics.mean(r[f"true_{kind}"] for r in iterations)
        est = [r[f"est_{kind}"] for r in iterations]
        mean = statistics.mean(est)
        out[kind] = [true, mean, mean - true, statistics.mean(r[f"se_{kind}"] for r in iterations),
                     statistics.stdev(est)]
    return out


def columns_of(d):
    """Table 1 Panel B stores lists per column; Panels A and C store one dict per iteration."""
    if isinstance(d, list):
        return d
    n = len(d["est_own"])
    return [{k: d[k][i] for k in d} for i in range(n)]


def write(table, header, body, note):
    with open(f"{OUT}/{table}.tex", "w") as f:
        f.write(f"% {table}: generated by tables/all_tables.py from simulation_results/. {note}\n")
        f.write(header + "\n" + "\n".join(body) + "\n\\bottomrule\n\\end{tabular}\n")
    WRITTEN.append(table)


def elasticity_table(table, panels, label_col, note):
    """Tables 1, A2, A4: rows of (label, own/cross, true, mean, bias, mean SE, SD)."""
    body = []
    for panel, title, rows in panels:
        if title:
            body.append(f"\\multicolumn{{7}}{{@{{}}l}}{{\\textit{{{title}}}}} \\\\")
        for i, (label, iterations) in enumerate(rows):
            s = summary(iterations)
            for kind in ("own", "cross"):
                lead = f"\\multirow{{2}}{{*}}{{{label}}}" if kind == "own" else ""
                body.append(f"{lead} & {kind} & " + " & ".join(f3(v) for v in s[kind]) + " \\\\")
            body.append("\\addlinespace" if i < len(rows) - 1 else "\\midrule")
        if body[-1] == "\\midrule" and panel == panels[-1][0]:
            body.pop()
    header = ("\\begin{tabular}{lcrrrrr}\n\\toprule\n" + label_col +
              " & Elasticity & True Value & Mean Estimate & Bias & Mean SE & Std. Dev. \\\\\n\\midrule")
    write(table, header, body, note)


def table_1():
    a, b, c = load("table_1_models.json"), load("table_5_supply.json"), load("table_4_extra_models.json")
    panels = [("A", "Panel A: Baseline Random-coefficient Logit Models", [(lab, a[k]) for k, lab in MODELS_A]),
              ("B", "Panel B: Supply-side Equilibrium", [(lab, columns_of(b[k])) for k, lab in MODELS_B]),
              ("C", "Panel C: Other Demand Models", [(lab, c[k]) for k, lab in MODELS_C])]
    elasticity_table("Table_1", panels, "Model", "Point-wise elasticity estimation.")


def table_2():
    d = load("table_6_literature.json")
    order = [("Logit_Wollmann", "Wollmann (2018) Logit", 2),
             ("RC_BLP", "BLP (1995) / CG (2020), RC Logit", 2),
             ("RC_Nevo", "Nevo (2001) / CG (2020), RC Logit", 3)]
    body = []
    for key, label, pd_ in order:
        r = d[key]
        for j in range(len(r["true_elas"])):
            te, be = r["true_elas"][j], r["bnn_elas_mean"][j]
            tp, bp, pb = r["true_p_star"][j], r["bnn_p_star_mean"][j], r["price_bias"][j]
            cells = [fnum(te, 2), fnum(be, 2), fnum(be - te, 2), fnum(tp, pd_), fnum(bp, pd_), fnum(pb, pd_)]
            lead = f"\\multirow{{4}}{{*}}{{{label}}}" if j == 0 else ""
            body.append(f"{lead} & {j + 1} & " + " & ".join(cells) + " \\\\")
        body.append("\\midrule")
    body.pop()
    header = ("\\begin{tabular}{lcrrrrrr}\n\\toprule\n & & \\multicolumn{3}{c}{Elasticity} & "
              "\\multicolumn{3}{c}{Pricing} \\\\\n\\cmidrule(lr){3-5} \\cmidrule(lr){6-8}\n"
              "DGP & Prod. & True $\\varepsilon$ & BNN $\\varepsilon$ & Bias & True $p^*$ & BNN $p^*$ & Bias \\\\\n\\midrule")
    write("Table_2", header, body, "Literature-calibrated DGPs; means over 10 Monte Carlo replications.")


def table_3():
    d = load("table_6_baseline_pricing.json")
    mean = statistics.mean
    body = []
    for key, label in (("logit", "Logit"), ("ind_rc", "Independent RC Logit"), ("corr_rc", "Correlated RC Logit")):
        r = d[key]
        tp, bp, bb = mean(r["true_p_star"]), mean(r["bnn_p_star_mean"]), mean(r["bnn_bias"])
        pp, pbias = mean(r["pyblp_p_star_mean"]), mean(r["pyblp_bias"])
        cells = [f3(tp), f3(bp), f3(bb), f"{r['bnn_time_mean']:.2f}s", f3(pp), f3(pbias),
                 f"{round(r['pyblp_time_mean']):,}s"]
        body.append(f"{label} & " + " & ".join(cells).replace(",", "{,}") + " \\\\")
    header = ("\\begin{tabular}{lrrrlrrl}\n\\toprule\n & & \\multicolumn{3}{c}{BNN} & \\multicolumn{3}{c}{PyBLP} \\\\\n"
              "\\cmidrule(lr){3-5} \\cmidrule(lr){6-8}\nModel & True $p^*$ & $p^*$ & bias & time & $p^*$ & bias & time \\\\\n\\midrule")
    write("Table_3", header, body, "Averages over the 4 products; timings are hardware-specific.")


def table_4():
    cols = ["Numba Runtime (Point Estimate)", "Numba Runtime (100 Bootstrap)",
            "PyTorch CPU Runtime (Point Estimate)", "PyTorch CPU Runtime (100 Bootstrap)",
            "PyTorch GPU Runtime (Point Estimate)", "PyTorch GPU Runtime (100 Bootstrap)"]
    body = []
    for fname, title in (("table_2_scalability.json", "Panel A: Correlated RC Logit, 4 products"),
                         ("table_2_scalability_20.json", "Panel B: Correlated RC Logit, 20 products")):
        body.append(f"\\multicolumn{{7}}{{@{{}}l}}{{\\textit{{{title}}}}} \\\\")
        for r in load(fname):
            n = f"{r['Sample Size']:,}"
            body.append(f"{n.replace(',', '{,}')} & " + " & ".join(f3(r[c]) for c in cols) + " \\\\")
        body.append("\\midrule")
    body.pop()
    header = ("\\begin{tabular}{lrrrrrr}\n\\toprule\n & \\multicolumn{2}{c}{Numba CPU} & \\multicolumn{2}{c}{PyTorch CPU}"
              " & \\multicolumn{2}{c}{PyTorch GPU} \\\\\n\\cmidrule(lr){2-3} \\cmidrule(lr){4-5} \\cmidrule(lr){6-7}\n"
              "Sample Size & Point & Bootstrap & Point & Bootstrap & Point & Bootstrap \\\\\n\\midrule")
    write("Table_4", header, body, "Seconds; hardware-specific.")


def tuning_grid(results, models, field):
    grid = {}
    for key, v in results.items():
        m, n, j = key.split("|")
        grid.setdefault(m, {}).setdefault(int(n), {})[int(j)] = v[field]
    return {lab: grid[m] for m, lab in models}


def tuning_table(table, panels):
    body = []
    for title, grid in panels:
        if title:
            body.append(f"\\multicolumn{{11}}{{@{{}}l}}{{\\textit{{{title}}}}} \\\\")
        for label, by_n in grid.items():
            for i, n in enumerate(OBS):
                cells = [str(by_n[n][j]) for j in PRODUCTS]
                lead = f"\\multirow{{4}}{{*}}{{{label}}}" if i == 0 else ""
                body.append(f"{lead} & {n:,} & ".replace(",", "{,}", 1 if not lead else 0) + " & ".join(cells) + " \\\\")
            body.append("\\midrule")
    body.pop()
    header = ("\\begin{tabular}{llrrrrrrrrr}\n\\toprule\n & & \\multicolumn{9}{c}{Number of Products} \\\\\n"
              "\\cmidrule(l){3-11}\nModel & Obs. & " + " & ".join(map(str, PRODUCTS)) + " \\\\\n\\midrule")
    write(table, header, body, "MSE-minimising subsampling size m.")


def table_5():
    res = {**load("table_3_tuning_full.json"), **load("table_3_tuning_full_extended.json")}
    tuning_table("Table_5", [("", tuning_grid(res, MODELS_A, "optimal_own"))])
    # The same optima in the layout read by figures/all_figures.py (Figure A2).
    grid = {}
    for key, v in res.items():
        m, n, j = key.split("|")
        grid.setdefault((m, int(n)), {})[int(j)] = v["optimal_own"]
    with open(f"{OUT}/table_3_opt_tuning_own.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["model", "observations"] + PRODUCTS)
        for (m, n) in sorted(grid):
            w.writerow([m, n] + [grid[(m, n)][j] for j in PRODUCTS])


def table_A3():
    res = {**load("table_3_tuning_full.json"), **load("table_3_tuning_full_extended.json")}
    rf = load("table_3_tuning_reduced_form.json")
    tuning_table("Table_A3", [
        ("Panel A: Discrete-choice Models for Cross Elasticity", tuning_grid(res, MODELS_A, "optimal_cross")),
        ("Panel B: Reduced-form Polynomial Models",
         tuning_grid(rf, [("RF_linear", "Reduced-form linear"), ("RF_quadratic", "Reduced-form quadratic")],
                     "optimal_own"))])


def table_A2():
    fname = "table_A2_robustness.json"
    if not os.path.exists(f"{RES}/{fname}"):
        print(f"Table_A2: {fname} not found; run simulation_codes/table_A2_robustness.py")
        return
    res = load(fname)["results"]
    titles = {"A": "Panel A: Varying sample size ($J=4$ products)", "B": "Panel B: Varying number of products ($T=320{,}000$)",
              "C": "Panel C: Varying number of products ($T=5{,}120{,}000$)"}
    panels = []
    for panel in "ABC":
        rows = []
        for v in res.values():
            if v["panel"] != panel:
                continue
            spec = f"T={v['T']:,}" if panel == "A" else f"J={v['J']}"
            rows.append((f"${spec.replace('=', ' = ').replace(',', '{,}')}$", v["iterations"]))
        if rows:
            panels.append((panel, titles[panel], rows))
    elasticity_table("Table_A2", panels, "Specification", "Robustness checks.")


def table_A4():
    fname = "table_A4_extra_primitives.json"
    if not os.path.exists(f"{RES}/{fname}"):
        print(f"Table_A4: {fname} not found; run simulation_codes/table_A4_extra_primitives.py")
        return
    res = load(fname)["results"]
    titles = {"A": "Panel A: $b_1 = 4, a_0 = -1.2, a_1 = 0.3, a_2 = 0.8$",
              "B": "Panel B: $b_1 = 1.2, a_0 = -4, a_1 = 0.8, a_2 = 0.3$"}
    panels = [(v["panel"], titles[v["panel"]], [("Correlated RC Logit", v["iterations"])])
              for v in res.values()]
    elasticity_table("Table_A4", panels, "Model", "Extra primitive parameter values.")


if __name__ == "__main__":
    for f in (table_1, table_2, table_3, table_4, table_5, table_A2, table_A3, table_A4):
        f()
    print("wrote " + ", ".join(f"{OUT}/{t}.tex" for t in WRITTEN))
